version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '10:00'
      timezone: Europe/Amsterdam
    target-branch: main
    pull-request-branch-name:
      separator: /
    commit-message:
      include: scope
      prefix: deps(github-actions)
    labels: [dependencies, github-actions]
    open-pull-requests-limit: 5

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: cron
      cronjob: '0 6 * * 6/3'
      timezone: Europe/Amsterdam
    target-branch: main
    pull-request-branch-name:
      separator: /
    commit-message:
      include: scope
      prefix: deps(uv)
    labels: [dependencies, uv]
    open-pull-requests-limit: 5
    versioning-strategy: auto
